crab submit -c crab3_analysisDY.py
crab submit -c crab3_analysisWA.py
crab submit -c crab3_analysisWAmlm.py
crab submit -c crab3_analysisWA_private.py
crab submit -c crab3_analysisWZ1.py
crab submit -c crab3_analysisST-tbarw.py
crab submit -c crab3_analysisST-tw.py
crab submit -c crab3_analysisSTs.py
crab submit -c crab3_analysisSTt.py
crab submit -c crab3_analysisSTtbar.py
crab submit -c crab3_analysisTTA1.py
crab submit -c crab3_analysisTTA2.py
crab submit -c crab3_analysisTTJets1.py
crab submit -c crab3_analysisTTJets2.py
crab submit -c crab3_analysisW3Jets1.py
crab submit -c crab3_analysisW3Jets2.py
crab submit -c crab3_analysisWAJJ.py
crab submit -c crab3_analysisWJets1.py
crab submit -c crab3_analysisWJets2.py
crab submit -c crab3_analysisWW1.py
crab submit -c crab3_analysisWW2.py
crab submit -c crab3_analysisWZ2.py
crab submit -c crab3_analysisZA.py
crab submit -c crab3_analysisZZ1.py
crab submit -c crab3_analysisZZ2.py
crab submit -c crab3_analysisele.py
crab submit -c crab3_analysisele_C.py
crab submit -c crab3_analysisele_D.py
crab submit -c crab3_analysisele_E.py
crab submit -c crab3_analysisele_F.py
crab submit -c crab3_analysisele_G.py
crab submit -c crab3_analysisele_H1.py
crab submit -c crab3_analysisele_H2.py
crab submit -c crab3_analysismu.py
crab submit -c crab3_analysismu_C.py
crab submit -c crab3_analysismu_D.py
crab submit -c crab3_analysismu_E.py
crab submit -c crab3_analysismu_F.py
crab submit -c crab3_analysismu_G.py
crab submit -c crab3_analysismu_H1.py
crab submit -c crab3_analysismu_H2.py
