#!/bin/bash

crab submit -c ./crab/crab3_analysis_DY_noPU_v1.py
crab submit -c ./crab/crab3_analysis_DY_noPU_v2.py
crab submit -c ./crab/crab3_analysis_DY_noPU_v3.py
crab submit -c ./crab/crab3_analysis_DY_noPU_v4.py
crab submit -c ./crab/crab3_analysis_DY_noPU_v5.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v1_ext.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v1.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v2_ext.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v2.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v3_ext.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v3.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v4_ext.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v4.py
crab submit -c ./crab/crab3_analysis_DY_PU200_v5.py
crab submit -c ./crab/crab3_analysis_QCD_noPU_v1.py
crab submit -c ./crab/crab3_analysis_QCD_PU200_v1.py
crab submit -c ./crab/crab3_analysis_QCD_PU200_v1_ext.py
crab submit -c ./crab/crab3_analysis_DY_PU200_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_PU200_GEN-SIM-RECO_v1_ext.py
crab submit -c ./crab/crab3_analysis_DY_noPU_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_QCD_PU200_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_QCD_PU200_GEN-SIM-RECO_v1_ext.py
crab submit -c ./crab/crab3_analysis_QCD_noPU_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_1J_PU200_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_1J_PU200_GEN-SIM-RECO_v1_ext.py
crab submit -c ./crab/crab3_analysis_DY_1J_noPU_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_2J_PU200_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_2J_PU200_GEN-SIM-RECO_v1_ext.py
crab submit -c ./crab/crab3_analysis_DY_2J_noPU_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_3J_PU200_GEN-SIM-RECO_v1.py
crab submit -c ./crab/crab3_analysis_DY_3J_noPU_GEN-SIM-RECO_v1.py
